// Currencies conforming to the ISO 4217 standard
import { computed } from "vue";
import type { ComputedRef } from "vue";
import type { MaybeComputedRef } from "@vueuse/shared";
import { resolveUnref } from "@vueuse/shared";

export enum Currency {
  AED = "aed",
  AFN = "afn",
  ALL = "all",
  AMD = "amd",
  ANG = "ang",
  AOA = "aoa",
  ARS = "ars",
  AUD = "aud",
  AWG = "awg",
  AZN = "azn",
  BAM = "bam",
  BBD = "bbd",
  BDT = "bdt",
  BGN = "bgn",
  BHD = "bhd",
  BIF = "bif",
  BMD = "bmd",
  BND = "bnd",
  BOB = "bob",
  BOV = "bov",
  BRL = "brl",
  BSD = "bsd",
  BTN = "btn",
  BWP = "bwp",
  BYN = "byn",
  BZD = "bzd",
  CAD = "cad",
  CDF = "cdf",
  CHE = "che",
  CHF = "chf",
  CHW = "chw",
  CLF = "clf",
  CLP = "clp",
  COP = "cop",
  COU = "cou",
  CRC = "crc",
  CUC = "cuc",
  CUP = "cup",
  CVE = "cve",
  CZK = "czk",
  DJF = "djf",
  DKK = "dkk",
  DOP = "dop",
  DZD = "dzd",
  EGP = "egp",
  ERN = "ern",
  ETB = "etb",
  EUR = "eur",
  FJD = "fjd",
  FKP = "fkp",
  GBP = "gbp",
  GEL = "gel",
  GHS = "ghs",
  GIP = "gip",
  GMD = "gmd",
  GNF = "gnf",
  GTQ = "gtq",
  GYD = "gyd",
  HKD = "hkd",
  HNL = "hnl",
  HRK = "hrk",
  HTG = "htg",
  HUF = "huf",
  IDR = "idr",
  ILS = "ils",
  INR = "inr",
  IQD = "iqd",
  IRR = "irr",
  ISK = "isk",
  JMD = "jmd",
  JOD = "jod",
  JPY = "jpy",
  KES = "kes",
  KGS = "kgs",
  KHR = "khr",
  KMF = "kmf",
  KPW = "kpw",
  KRW = "krw",
  KWD = "kwd",
  KYD = "kyd",
  KZT = "kzt",
  LAK = "lak",
  LBP = "lbp",
  LKR = "lkr",
  LRD = "lrd",
  LSL = "lsl",
  LYD = "lyd",
  MAD = "mad",
  MDL = "mdl",
  MGA = "mga",
  MKD = "mkd",
  MMK = "mmk",
  MNT = "mnt",
  MOP = "mop",
  MRU = "mru",
  MUR = "mur",
  MVR = "mvr",
  MWK = "mwk",
  MXN = "mxn",
  MXV = "mxv",
  MYR = "myr",
  MZN = "mzn",
  NAD = "nad",
  NGN = "ngn",
  NIO = "nio",
  NOK = "nok",
  NPR = "npr",
  NZD = "nzd",
  OMR = "omr",
  PAB = "pab",
  PEN = "pen",
  PGK = "pgk",
  PHP = "php",
  PKR = "pkr",
  PLN = "pln",
  PYG = "pyg",
  QAR = "qar",
  RON = "ron",
  RSD = "rsd",
  CNY = "cny",
  RUB = "rub",
  RWF = "rwf",
  SAR = "sar",
  SBD = "sbd",
  SCR = "scr",
  SDG = "sdg",
  SEK = "sek",
  SGD = "sgd",
  SHP = "shp",
  SLL = "sll",
  SOS = "sos",
  SRD = "srd",
  SSP = "ssp",
  STN = "stn",
  SVC = "svc",
  SYP = "syp",
  SZL = "szl",
  THB = "thb",
  TJS = "tjs",
  TMT = "tmt",
  TND = "tnd",
  TOP = "top",
  TRY = "try",
  TTD = "ttd",
  TWD = "twd",
  TZS = "tzs",
  UAH = "uah",
  UGX = "ugx",
  USD = "usd",
  USN = "usn",
  UYI = "uyi",
  UYU = "uyu",
  UYW = "uyw",
  UZS = "uzs",
  VED = "ved",
  VES = "ves",
  VND = "vnd",
  VUV = "vuv",
  WST = "wst",
  XAF = "xaf",
  XAG = "xag",
  XAU = "xau",
  XBA = "xba",
  XBB = "xbb",
  XBC = "xbc",
  XBD = "xbd",
  XCD = "xcd",
  XDR = "xdr",
  XOF = "xof",
  XPD = "xpd",
  XPF = "xpf",
  XPT = "xpt",
  XSU = "xsu",
  XTS = "xts",
  XUA = "xua",
  XXX = "xxx",
  YER = "yer",
  ZAR = "zar",
  ZMW = "zmw",
  ZWL = "zwl",
}

// TODO: move to store.
const currency = Currency.EUR;
const language = "nl-NL";

export const useCurrency = (
  value: MaybeComputedRef<number>
): ComputedRef<string> => {
  return computed(() => {
    return formatNumber(resolveUnref(value), {
      style: "currency",
      currencyDisplay: "narrowSymbol",
    });
  });
};

export const useFormatNumber = (
  value: MaybeComputedRef<number>,
  options: Intl.NumberFormatOptions = {}
): ComputedRef<string> => {
  return computed(() => {
    return formatNumber(resolveUnref(value), options);
  });
};

export const formatNumber = (
  value: number,
  options: Intl.NumberFormatOptions = {}
): string => {
  return new Intl.NumberFormat(language, {
    ...options,
    currency,
  }).format(value);
};
